### ISSUE TITLE
collectd unable to connect to localhost:2003

### ISSUE THREAD

**Issue by japplewhite** [Tendrl/performance-monitoring#213] opened 2017-06-22 21:17 UTC
It looks like the default config doesn't work. Is this error valid?

Jun 22 21:05:45 stg01 collectd: write_graphite plugin: Connecting to localhost.localdomain:2003 via tcp failed. The last error was: failed to connect to remote host: Connection refused

**Comment by anmolbabu** [comment] 2017-06-23 03:13
@japplewhite I would like to know the following:

1. Does localhost.localdomain actually resolve to the graphite server from the node where you see this 
    error....
    Is graphite server local to the node on which you see this error?
2. Is the firewall disabled with selinux in permissive mode??
3. Which branch are the rpms from... I assume the rpms you are using are from release 1.4.2.https://github.com/Tendrl/node-monitoring/issues/61 which is not fixed in 1.4.2 release rpms but available in develop and master.. So, it might be possible that the hostname of performance-monitoring node is localhost.localdomain but that is not dns resolvable from the node where you see this error...So the bug is that graphite server address in conf file was not used to configure a collectd's write plugin(which pushes stats to graphite) but instead we were using the hostname of the performance-monitoring node to configure the graphite write plugin but that has been fixed now in develop and master and should be available in next release...

**Comment by japplewhite** [comment] 2017-06-23 19:56
@anmolbabu No - in this case the storage node was named tendrl and was at another IP that is not in the hosts file or dns for the stg01 host where this log appeared. I think relying on naming rather than IP addresses or explicit variables for this that come from tendrl-ansible is asking for problems. Many admins never set naming up.

**Comment by anmolbabu** [comment] 2017-06-24 03:29
@japplewhite The problem is the node might have multiple ip addresses(multiple n/w interface nodes) so how do we figure out on which ip, the graphite server will be accessible...so to avoid this we have a performance-monitoring.conf file entry where we specifically take the ip/hostname(anything can be passed) of the graphite server and we use it to configure collectd.. The PR with this change is merged in develop and master but not available in release 1.4.2 branch currently...

**Comment by japplewhite** [comment] 2017-06-26 14:14
@anmolbabu This is essentially the conclusion I came to as well. I think the best method is to set this via variables that are explicitly defined in tendrl-ansible/site.yml otherwise we are guessing at the correct implementation.

**Comment by japplewhite** [comment] 2017-06-26 14:14
@mbukatov - looks like this should be included in the playbook

**Comment by mbukatov** [comment] 2017-06-26 14:24
We need to update [documentation](https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference) first, it would help me to understand where the problem actually is. Btw is this related to the question raised here https://www.redhat.com/archives/tendrl-devel/2017-June/msg00106.html (I'm asking about ip address of carbon among other things)?

**Comment by anmolbabu** [comment] 2017-07-04 05:39
@mbukatov Yes this is the graphite ip...
I think nothing new needs to be done here, there was a bug that although this field existed it was not used internally which has now been fixed . So, I think this can be closed...

Please reopen this if found relevant to master again...

**Closed** 2017-07-18 11:04 UTC
